# Generated by Django 5.0 on 2024-02-15 20:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schooldatamodel',
            fields=[
                ('School_Id', models.AutoField(primary_key=True, serialize=False)),
                ('School_Name', models.CharField(max_length=100)),
                ('School_Email', models.EmailField(max_length=100)),
                ('School_Key', models.CharField(max_length=100)),
                ('School_Established', models.DateField(default=django.utils.timezone.now)),
                ('School_State', models.CharField(max_length=50)),
                ('School_District', models.CharField(max_length=50)),
                ('School_Locality', models.CharField(max_length=50)),
                ('School_Pincode', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'SchoolData',
            },
        ),
        migrations.CreateModel(
            name='Staffdatamodel',
            fields=[
                ('Staff_ID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Staff_Firstname', models.CharField(max_length=100)),
                ('Staff_Lastname', models.CharField(max_length=100)),
                ('Staff_Profilepic', models.ImageField(default='', upload_to='static/')),
                ('Staff_Adharpic', models.ImageField(default='', upload_to='static/')),
                ('Staff_Qualification', models.CharField(choices=[('Post Graduation', 'Post Graduate'), ('Graduation', 'Graduate'), ('Higher Secondary School', 'HS School')], max_length=50)),
                ('Staff_JoiningDate', models.DateField(default=django.utils.timezone.now)),
                ('Staff_Salary', models.CharField(max_length=10)),
                ('Staff_Position', models.CharField(choices=[('Teacher_Level A+', 'TA+'), ('Teacher_Level A', 'TA'), ('Teacher_Level B', 'B'), ('Teacher_Level C', 'C'), ('Support Staff', 'SST')], max_length=20)),
                ('Staff_State', models.CharField(max_length=50)),
                ('Staff_District', models.CharField(max_length=50)),
                ('Staff_Locality', models.CharField(max_length=50)),
                ('Staff_Pincode', models.CharField(max_length=50)),
                ('School_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='ManageSchool.schooldatamodel')),
            ],
            options={
                'db_table': 'StaffData',
            },
        ),
        migrations.CreateModel(
            name='Studentdatamodel',
            fields=[
                ('Student_Id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Student_Firstname', models.CharField(max_length=20)),
                ('Student_Lastname', models.CharField(max_length=20)),
                ('Student_DateofBirth', models.DateField(default=django.utils.timezone.now)),
                ('Student_Passportphoto', models.ImageField(default='', upload_to='static/')),
                ('Student_Adharphoto', models.ImageField(default='', upload_to='static/')),
                ('Student_CurrentStandard', models.CharField(max_length=10)),
                ('Student_PreviousStandard', models.CharField(max_length=10)),
                ('Student_Qualification', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=50)),
                ('Student_Contact', models.CharField(max_length=20)),
                ('Student_Joindate', models.DateField(default=django.utils.timezone.now)),
                ('StudentID_Validation', models.DateField(default=django.utils.timezone.now)),
                ('Student_State', models.CharField(max_length=50)),
                ('Student_District', models.CharField(max_length=50)),
                ('Student_Locality', models.CharField(max_length=50)),
                ('Student_Pincode', models.CharField(max_length=50)),
                ('Student_School', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='ManageSchool.schooldatamodel')),
            ],
            options={
                'db_table': 'StudentData',
            },
        ),
    ]
